using System;
using System.ComponentModel.DataAnnotations.Schema;
using Volo.Abp.MultiTenancy;
using VTECHERP.Enums;

namespace VTECHERP.Entities
{
    [Table("Debts")]
    public class Debt : BaseEntity<Guid>, IMultiTenant
    {
        /// <summary>
        /// Mã công nợ
        /// </summary>
        public string Code { get; set; }
        /// <summary>
        /// Mã giao dịch
        /// </summary>
        /// 
        public Guid TransactionId { get; set; }
        /// <summary>
        /// Loại phiếu 
        /// </summary>
        public TicketTypes? TicketType { get; set; }
        /// <summary>
        /// Mã KH
        /// </summary>
        public Guid? CustomerId { get; set; }
        /// <summary>
        /// Mã nhà cung cấp
        /// </summary>
        public Guid? SupplierId { get; set; }
        /// <summary>
        /// Người phụ trách
        /// </summary>
        public Guid? EmployeeId { get; set; }

        /// <summary>
        /// Của hàng phụ trách
        /// </summary>
        public Guid? StoreId { get; set; }
        public bool HasCod { get; set; }
        /// <summary>
        /// Có (phải trả)
        /// </summary>
        public decimal Credits { get; set; }
        /// <summary>
        /// Nợ (phải thu)
        /// </summary>
        public decimal Debts { get; set; }
        /// <summary>
        /// Hạn nợ
        /// </summary>
        public DateTime Deadline { get; set; }
        /// <summary>
        /// Công nợ được sinh tự động
        /// </summary>
        public bool IsAutoGenerated { get; set; }
        /// <summary>
        /// Ghi chú
        /// </summary>
        public string Note { get; set; }
        /// <summary>
        /// Đối tượng
        /// </summary>
        public AudienceTypes? AudienceType { get; set; }
        public Guid? AudienceId { get; set; }
        /// <summary>
        /// Ngày thu chi
        /// </summary>
        public DateTime TransactionDate { get; set; }
        /// <summary>
        /// Id bút toán
        /// </summary>
        public Guid? EntryId { get; set; }
        /// <summary>
        /// Loại chứng từ
        /// </summary>
        public DocumentTypes DocumentType { get; set; }
        /// <summary>
        /// Id chứng từ
        /// </summary>
        public Guid? DocumentId { get; set; }
        /// <summary>
        /// Loại tiền tệ
        /// </summary>
        public Currencies Currency { get; set; } = Currencies.VND;
    }
}
