using System;
using System.ComponentModel.DataAnnotations.Schema;
using Volo.Abp.MultiTenancy;
using VTECHERP.Enums;

namespace VTECHERP.Entities
{
    [Table("DebtReports")]
    public class DebtReport : BaseEntity<Guid>, IMultiTenant
    {
        /// <summary>
        /// Năm
        /// </summary>
        public int Year { get; set; }
        /// <summary>
        /// Quý
        /// </summary>
        public int? Quarter { get; set; }
        /// <summary>
        /// Tháng
        /// </summary>
        public int? Month { get; set; }
        /// <summary>
        /// Phải thu đầu kỳ
        /// </summary>
        public decimal BeginOfPeriodCredit { get; set; }
        /// <summary>
        /// Phải trả đầu kỳ
        /// </summary>
        public decimal BeginOfPeriodDebt { get; set; }
        /// <summary>
        /// Phải thu giữa kỳ
        /// </summary>
        public decimal PeriodCredit { get; set; }
        /// <summary>
        /// Phải trả giữa kỳ
        /// </summary>
        public decimal PeriodDebt { get; set; }
        /// <summary>
        /// Phải thu cuối kỳ
        /// </summary>
        public decimal EndOfPeriodCredit { get; set; }
        /// <summary>
        /// Phải trả cuối kỳ
        /// </summary>
        public decimal EndOfPeriodDebt { get; set; }
        /// <summary>
        /// Báo cáo công nợ được sinh tự động
        /// </summary>
        public bool IsAutoGenerated { get; set; }
        /// <summary>
        /// Mã nhà cung cấp // Khách hàng
        /// </summary>
        public Guid? AudienceId { get; set; } = Guid.Empty;
        /// <summary>
        /// Đối tượng
        /// </summary>
        public AudienceTypes? AudienceType { get; set; }
    }
}
