using System;
using System.Collections.Generic;
using System.Text;
using VTECHERP.Enums;

namespace VTECHERP.Debts
{
    public class DebtDto
    {
        public Guid Id { get; set; }
        /// <summary>
        /// Mã công nợ
        /// </summary>
        public string Code { get; set; }
        /// <summary>
        /// Loại phiếu 
        /// </summary>
        public TicketTypes? TicketType { get; set; }
        /// <summary>
        /// Chứng từ
        /// </summary>
        public string DocumentCode { get; set; }
        /// <summary>
        /// Mã giao dịch
        /// </summary>
        public Guid TransactionId { get; set; }
        /// <summary>
        /// Mã KH
        /// </summary>
        public Guid? CustomerId { get; set; }
        /// <summary>
        /// Id nhà cung cấp
        /// </summary>
        public Guid? SupplierId { get; set; }
        /// <summary>
        /// Mã nhà cung cấp
        /// </summary>
        public string SupplierCode { get; set; }
        /// <summary>
        /// Tên nhà cung cấp
        /// </summary>
        public string SupplierName { get; set; }

        /// <summary>
        /// Tên nhà cung cấp
        /// </summary>
        public SupplierOrigin? SupplierType { get; set; }
        /// <summary>
        /// Số điện thoại
        /// </summary>
        public string PhoneNumber { get; set; }
        /// <summary>
        /// Người phụ trách
        /// </summary>
        public Guid EmployeeId { get; set; }
        /// <summary>
        /// Nợ (phải thu)
        /// </summary>
        public decimal BeginCredit { get; set; }
        /// <summary>
        /// Có (phải trả)
        /// </summary>
        public decimal BeginDebt { get; set; }
        /// <summary>
        /// Nợ (phải thu)
        /// </summary>
        public decimal Credit { get; set; }
        /// <summary>
        /// Có (phải trả)
        /// </summary>
        public decimal Debt { get; set; }
        /// <summary>
        /// Nợ (phải thu)
        /// </summary>
        public decimal EndCredit { get; set; }
        /// <summary>
        /// Có (phải trả)
        /// </summary>
        public decimal EndDebt { get; set; }
        /// <summary>
        /// Hạn nợ
        /// </summary>
        public DateTime Deadline { get; set; }
        public DateTime CreationTime { get; set; }
        /// <summary>
        /// Công nợ được sinh tự động
        /// </summary>
        public bool IsAutoGenerated { get; set; }
        /// <summary>
        /// Tỉ giá NDT - VND
        /// </summary>
        public decimal? Rate { get; set; } = 1;
        /// <summary>
        /// Đối tượng
        /// </summary>
        public AudienceTypes? AudienceType { get; set; }
        /// <summary>
        /// Ngày thu chi
        /// </summary>
        public DateTime TransactionDate { get; set; }
        /// <summary>
        /// Id chứng từ
        /// </summary>
        public Guid? DocumentId { get; set; }
    }
}
