namespace VTECHERP.Constants
{
    public class ErrorMessages
    {
        public const string Unexpected = "unexpected";

        public class Common
        {
            public const string Existed = "existed";
            public const string NotExist = "not_exist";
            public const string Null = "null";
            public const string NullOrWhiteSpace = "null_or_whitespace";
            public const string CanNotDelete = "can_not_delete";
            public const string CanNotChange = "can_not_change";
            public const string NumericLessThanZero = "numeric_less_than_zero";
            public const string Duplicate = "duplicate";
            public const string Async = "asynchronous";
            public const string ModifyAutoGeneratedData = "modify_auto_generated";
            public const string ModifyDeadline = "modify_deadline";
            public const string Required = "{0} là bắt buộc";
            public const string RequestNotNull = "Không nhận được dữ liệu đầu vào.";
            public const string NotFound = "Không tìm thấy dữ liệu phù hợp.";
        }

        public class UserStore
        {
            public const string StoreNotDefine = "Người dùng chưa được cấu hình vào cửa hàng";
        }

        public class Accounts
        {
            public const string Base = "acciount";
            public const string NotExist = $"{Base}.{Common.NotExist}";
            public const string Existed = $"{Base}.{Common.Existed}";
        }

        public class Entries
        {
            public const string Base = "entry";
            public const string NotExist = $"{Base}.{Common.NotExist}";
            public const string Existed = $"{Base}.{Common.Existed}";
        }

        public class Supplier
        {
            public const string Base = "Supplier";
            public const string NotExist = $"{Base}.{Common.NotExist}";
            public const string Existed = $"{Base}.{Common.Existed}";
        }

        public class Store
        {
            public const string Base = "Store";
            public const string NotExist = $"{Base}.{Common.NotExist}";
            public const string Existed = $"{Base}.{Common.Existed}";
        }

        public class Product
        {
            public const string Base = "Product";
            public const string NotExist = $"{Base}.{Common.NotExist}";
            public const string Existed = $"{Base}.{Common.Existed}";
            public const string Duplicate = $"{Base}.{Common.Duplicate}";
            public const string Null = $"{Base}.{Common.Null}";
            public const string DuplicateVN = $"Tồn tại sản phẩm trùng lặp.";
            public const string NotExistVN = $"Không tìm thấy thông tin sản phẩm.";
        }

        public class SaleOrder
        {
            public const string Base = "SaleOrder";
            public const string NotExist = $"{Base}.{Common.NotExist}";
            public const string CanNotDeleteStatusFinished = $"{Base}.{Common.CanNotDelete}.StatusComplete";
            public const string CanNotDeleteStatusConfirmed = $"{Base}.{Common.CanNotDelete}.StatusConfirmed";
            public const string NullOrWhiteSpace = $"{Base}.{Common.NullOrWhiteSpace}";
            public const string Existed = $"{Base}.{Common.Existed}";
            public const string NumericLessThanZero = $"{Base}.{Common.NumericLessThanZero}";
            public const string ConfirmNotLack = $"{Base}.{Common.CanNotChange}.ConfirmNotLack";
            public const string IsComplete = $"{Base}.{Common.CanNotChange}.IsComplete";
        }

        public class SaleOrderLine
        {
            public const string Base = "SaleOrderLine";
            public const string ImportQuantityNotZero = "ImportQuantity_not_zero";
            public const string RQLessIQ = "RequestQuantity_less_ImportQuantity";
            public const string AllSaleOrdrLine = "All_SaleOrderLine";

            public const string NotExist = $"{Base}.{Common.NotExist}";
            public const string Null = $"{Base}.{Common.Null}";
            public const string Existed = $"{Base}.{Common.Existed}";
            public const string CanNotDelete = $"{Base}.{Common.CanNotDelete}: {ImportQuantityNotZero}";
            public const string CanNotDeleteAll = $"{Base}.{Common.CanNotDelete}: {AllSaleOrdrLine}";
            public const string CanNotChange = $"{Base}.{Common.CanNotChange}: {RQLessIQ}";
            public const string NumericLessThanZero = $"{Base}.{Common.NumericLessThanZero}";
        }

        public class WarehouseTransferBill
        {
            public const string Base = "WarehouseTransferBill";

            public const string Null = $"{Base}.{Common.Null}";
            public const string Duplicate = $"{Base}.{Common.Duplicate}";
            public const string SQLessQ = "StockQuantity_less_Quantity";
            public const string NumericLessThanZero = $"{Base}.{Common.NumericLessThanZero}";
            public const string NotExist = $"{Base}.{Common.NotExist}";
            public const string CanNotApprove = $"{Base}.{Common.CanNotChange}";
            public const string NotDraftStatus = $"{Base}.{Common.CanNotDelete}.NotDraftStatus";
            public const string NotInDeliveryStatus = $"{Base}.{Common.CanNotDelete}.NotInDeliveryStatus";
            public const string CanNotConfirmNotInDelivery = $"{Base}.{Common.CanNotChange}.CanNotConfirmNotInDelivery";

            
            public const string SourceStore = "Cửa hàng đi";
            public const string DestinationStore = "Cửa hàng đến";
            public const string NotExistVN = "không tồn tại.";
            public const string NotDuplicate = $"{SourceStore} không được trùng {DestinationStore}";
            public const string SQLessQVN = "Số lượng tồn không được lớn hơn số lượng.";
            public const string NumericLessThanZeroVN = $"Số lượng không được nhỏ hơn không.";



        }

        public class WarehouseTransferBillProduct
        {
            public const string Base = "WarehouseTransferBillProduct";

            public const string NotExist = $"{Base}.{Common.NotExist}";
            public const string Null = $"{Base}.{Common.Null}";
            public const string Async = $"{Base}.{Common.Async}";
            public const string SQOtherAQConfirm = $"{Base}.StockQuantity_other_ConfirmQuantity";
            public const string SQLessAQ = $"{Base}.StockQuantity_less_ApproveQuantity";
            public const string AQLessZero = $"{Base}.ApproveQuantity_less_Zero";

            public const string NullVN = $"Danh sách sản phẩm không được đê trống";
        }

        public class DraftTicket
        {
            public const string Base = "DraftTicket";

            public const string Null = $"{Base}.{Common.Null}";
            public const string Duplicate = $"{Base}.{Common.Duplicate}";
            public const string SQLessQ = "StockQuantity_less_Quantity";
            public const string NumericLessThanZero = $"{Base}.{Common.NumericLessThanZero}";
            public const string NotExist = $"{Base}.{Common.NotExist}";
            public const string CanNotApprove = $"{Base}.{Common.CanNotChange}";
            public const string NotDraft_CancelStatus = $"{Base}.{Common.CanNotDelete}.NotDraft&CancelStatus";
            public const string NotInDeliveryStatus = $"{Base}.{Common.CanNotDelete}.NotInDeliveryStatus";
            public const string CanNotConfirmNotInDelivery = $"{Base}.{Common.CanNotChange}.CanNotConfirmNotInDelivery";
        }

        public class DraftTicketProduct
        {
            public const string Base = "DraftTicketProdut";

            public const string NotExist = $"{Base}.{Common.NotExist}";
            public const string Null = $"{Base}.{Common.Null}";
            public const string Async = $"{Base}.{Common.Async}";
            public const string SQOtherAQConfirm = $"{Base}.StockQuantity_other_ConfirmQuantity";
            public const string SQLessAQ = $"{Base}.StockQuantity_less_ApproveQuantity";
            public const string AQLessZero = $"{Base}.ApproveQuantity_less_Zero";
        }

        public class WarehousingBills
        {
            public const string Base = "warehousing";
            public const string CanNotExport = $"{Base}.{Common.CanNotDelete}";
            public const string NotExist = $"{Base}.{Common.NotExist}";
            public const string TotalDiscountLarge = $"{Base}.total_discount_large";
            public const string ProductDiscountLarge = $"{Base}.product_discount_large";
            public const string VATLackBillInfo = $"{Base}.vat_bill_info";
            public const string CashLackBillInfo = $"{Base}.cash_bill_info";
            public const string BankLackBillInfo = $"{Base}.bank_bill_info";
            public const string AudienceNull = $"{Base}.audience_null";
        }

        public class StoreProducts
        {
            public const string Base = "store_product";
            public const string NotExist = $"{Base}.{Common.NotExist}";
            public const string LackOfStock = $"{Base}.lack_of_stock";
            public const string Existed = $"{Base}.{Common.Existed}";
            public const string Duplicate = $"{Base}.{Common.Duplicate}";
            public const string Null = $"{Base}.{Common.Null}";
        }

        public class WarehousingBillLogs
        {
            public const string Base = "warehousing_logs";
            public const string NotExist = $"{Base}.{Common.NotExist}";
        }

        public class DebtReminderLog
        {
            public const string Base = "DebtReminderLog";

            public const string Null = $"{Base}.{Common.Null}";
            public const string Duplicate = $"{Base}.{Common.Duplicate}";
            public const string NumericLessThanZero = $"{Base}.{Common.NumericLessThanZero}";
            public const string NotExist = $"Không tìm thấy thông tin khách hàng.";
            public const string NotCreate = $"Khách hàng không thuộc phụ trách.";
            public const string CanNotApprove = $"{Base}.{Common.CanNotChange}";
        }

        public class User
        {
            public const string Base = "User";

            public const string NameRequired = "Họ và tên không được để trống.";
            public const string UseNameRequired = "Tên đăng nhập không được để trống.";
            public const string PhoneNumberRequired = "Số điện thoại không được để trống.";
            public const string MainStoreRequired = "Cửa hàng chính không được để trống.";

            public const string UserNameIsExist = "Tên đăng nhập đã được sử dụng.";
            public const string EmailIsExist = "Địa chỉ Email đã được sử dụng.";
            public const string PhoneIsExist = "Địa chỉ Email đã được sử dụng.";
            public const string MainStoreNotExist = "Không tìm thấy cửa hàng chính trong hệ thống.";
            public const string ExtraStoreNotExist = "Có cửa hàng phụ không tồn tại trong hệ thống.";
            public const string RoleNotExist = "Không tim thấy nhóm quyền mẫu trong hệ thống.";

            public const string PhoneNumberInCorrect = "Số điện thoại không đúng định dạng.";
            public const string EmailInCorrect = "Email không đúng định dạng.";
        }

        public class ProductCategory
        {
            public const string Base = "Danh mục sản phẩm";
            public const string ParentCategory = "Danh mục sản phẩm cha";
            public const string CategoryCode = "Mã danh mục";
            public const string Name = "Tên danh mục";
            public const string Ratio = "Tỷ lệ";
            public const string Manager = "Người phụ trách";
            public const string Status = "Trạng thái";

            public const string BaseNotNull = $"{Base} không có thông tin.";
            public const string BaseNotExist = $"{Base} không tồn tại.";
            public const string BaseExistProduct = $"{Base} có tồn tại sản phẩm.";
            public const string BaseChildExistProduct = $"{Base} con có tồn tại sản phẩm.";

            public const string ParentCategoryNotExist = $"{ParentCategory} không tồn tại.";
            public const string ParentCategoryInActive = $"{ParentCategory} không hoạt động.";
            public const string ParentCategoryInCorrect = $"{ParentCategory} đang là con của danh mục khác.";

            public const string CategoryCodeNotNull = $"{CategoryCode} không được để trống.";
            public const string CategoryCodeIsExist = $"{CategoryCode} đã tồn tại.";

            public const string NameNotNull = $"{Name} không được để trống.";
            public const string NameIsExist = $"{Name} đã tồn tại.";

            public const string RatioNotNull = $"{Ratio} không được để trống.";
            public const string RatioInCorrect = $"{Ratio} Lớn hơn 0 và nhỏ hơn hoặc bằng 100.";

            public const string ManagerNotNull = $"{Manager} không được để trống.";
            public const string ManagerNotExist = $"{Manager} không tồn tại.";

            public const string StatusInCorrect = $"{Status} không tồn tại.";
        }

        public class TenantError
        {
            public const string InputInCorrect = "Không tìm thấy dữ liệu tương ứng";
            public const string Enterprise = "Doanh nghiệp";
            public const string Agency = "Đại lý";
            public const string SaleOrder = "Phiếu đặt hàng";
            public const string WarehousingBill = "Đơn xuất nhập kho";
            public const string BillCustomer = "Hóa đơn bán hàng";

            public const string Name = "Tên";
            public const string PhoneNumber = "Số điện thoại";
            public const string Email = "Mail";
            public const string Province = "Thành phố";
            public const string District = "Huyện";
            public const string Address = "Địa chỉ";
            public const string Expiration = "Ngày hết hạn";
            public const string EnterpriseLink = "Doanh nghiệp liên kết";
            public const string Institute = "Tổ chức";
            public const string UserName = "Tên đăng nhập";
            public const string Password = "Mật khẩu";
            public const string Module = "Module";
            public const string Status = "Trạng thái";

            public const string NotNull = "không được để trống.";
            public const string NotExist = "không tồn tại.";
            public const string IsExist = "đã tồn tại.";
            public const string InCorrect = "không đúng định dạng.";
            public const string ExpirationInCorrect = "phải lớn hơn hoặc bằng ngày hiện tại.";
            public const string InActive = "không hoạt động.";
            public const string NotIn = "không thuộc";
        }

        public class CarrierShipping
        {
            public const string WrongCarrier = "Hình thức vận chuyển không thích hợp";
            public const string IntegrationError = "Lỗi tích hợp";
        }

        public class StoreReportMesage
        {
            public const string DateFrom = "Ngày đến ";
            public const string DateFromNotNull = $"{DateFrom} không được để trống.";
        }
    }
}